### PR TITLE
Dropped enabling xinetd via insserv

### PR DESCRIPTION
**Pull request by mchf**
bnc#1026027

### CODE REVIEW

**Comment by mchf** [comment]
@jsmeix Another piece for review. Thx

**Comment by jsmeix** [comment]
Furthermore keep the error messages mor meaningful
according to what the code actually does, i.e. use
<pre>
echo "Cannot reload or start and enable xinetd (no $XINETD_SYSTEMD_UNIT_FILE)" 1>&2
</pre>
and
<pre>
echo "Cannot reload xinetd (no $XINETD_SYSTEMD_UNIT_FILE)" 1>&2
</pre>

**Comment by mchf** [comment]
@jsmeix updated according your comments

**Comment by mchf** [comment]
@jsmeix thanks for review

**Pull request merged**
