### PR TITLE
Removed dependency in insserv

### PR DESCRIPTION
**Pull request by mchf**
bnc#1026027

Notes:
- AFAIK for HP these SysV services were replaced by systemd's hplip-printer@.service

### CODE REVIEW

**Comment by mchf** [comment]
@jsmeix Could you pls review?

**Comment by jsmeix** [comment]
@mchf 
you can remove all code that deals
with /etc/init.d/hplip and/or /etc/init.d/ptal cf.
/usr/lib/YaST2/bin/setup_ptal_scanner_service and
/usr/lib/YaST2/bin/setup_hplip_scanner_service
because since a longer time HPLIP does no longer
provide any files in /etc/init.d/.
Since a longer time HPLIP does no longer provide any services
so that you can remove all code that deals with services.

**Comment by mchf** [comment]
yes, that is the plan. I'll ask you for another review once I'm done.

Thanks for comments.

**Comment by mchf** [comment]
@jsmeix dropped all references to hplip and ptal sysv services. Could you pls re-check it?

I also did some quick grep and found out that only ptal service is in use

**Comment by jsmeix** [comment]
The changelog comment is wrong becauseas far as I know
neither the service "hplip" nor the service "ptal"
is "supported by systemd for sometime already"
because since a longer time HPLIP does no longer
provide or need any special HPLIP service.

**Comment by mchf** [comment]
@jsmeix does it make more sense now?

**Comment by jsmeix** [comment]
@mchf 
yes, now the changelog entry is o.k.
( the simpler the better ;-)

**Comment by mchf** [comment]
@jreidinger @jsmeix thanks for reviews

**Pull request merged**
